name: ppob-service-hesda

services:
  ppob-service:
    container_name: ppob-service-hesda
    image: rijalarfani/ppob-service-hesda:1.0.0
    ports:
      - "8001:8001"
    env_file:
      - .env
    restart: unless-stopped
